name: Jira Add Assignee
description: Add an assignee to an issue
branding:
  icon: 'align-left'
  color: 'blue'
inputs:
  issue:
    description: Key of the issue to be commented on
    required: true
  assignee:
    description: Assignee
    required: true
runs:
  using: 'node12'
  main: './dist/index.js'
